# DataSource
spring:
  datasource:
    username: koorung
    password: 1234
    url: jdbc:mariadb://localhost:3306/jwt
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA Option
  jpa:
    #    open-in-view: false  -> osiv설정을 끄면 뷰영역까지 영속성 컨텍스트가 유지되지 않는다.
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# Logging
logging:
  level:
    org.hibernate.type.descriptor.sql: trace